### ISSUE TITLE
Error in unpickling DateTime object having '+NNNN' timezone

### ISSUE THREAD

**Issue by fdiary** [zopefoundation/DateTime#3]
Hi,

We cannot unpickle the pickled result of a DateTime object having '+NNNN' timezone.

With 4.1, it is possible for +0300, but not possible for +0430 (Afghanistan timezone).

```
>>> from DateTime import DateTime
>>> a=DateTime('2007/01/02 12:34:56.789 +0300')
>>> a._tz
'GMT+3'
>>> a._timezone_naive
False
>>> a.tzoffset()
10800
>>> b = DateTime()
>>> b.__setstate__(a.__getstate__())
>>> b._tz
'GMT+3'
>>> a == b
True
>>> a=DateTime('2007/01/02 12:34:56.789 +0430')
>>> a._tz
'+0430'
>>> a._timezone_naive
True
>>> a.tzoffset()
16200
>>> b = DateTime()
>>> b.__setstate__(a.__getstate__())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/DateTime/DateTime.py", line 458, in __setstate__
    self._parse_args(value[0], value[2])
  File "/path/to/DateTime/DateTime.py", line 789, in _parse_args
    tz = _TZINFO._zmap[tz.lower()]
KeyError: '+0430'
```

With 3.0.3, it is not possible even for +0300.

```
>>> from DateTime import DateTime
>>> a=DateTime('2007/01/02 12:34:56.789 +0300')
>>> a._tz
'+0300'
>>> a._timezone_naive
True
>>> a.__getstate__()
(1167730496.789, True, '+0300')
>>> a.tzoffset()
10800
>>> b = DateTime()
>>> b.__setstate__(a.__getstate__())
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/path/to/DateTime/DateTime.py", line 455, in __setstate__
    self._parse_args(value[0], value[2])
  File "/path/to/DateTime/DateTime.py", line 787, in _parse_args
    tz = _TZINFO._zmap[tz.lower()]
KeyError: '+0300'
```

With DateTime 2.12.8, it is possible for both +0300 and +0430.

```
>>> from DateTime import DateTime
>>> a = DateTime('2007/01/02 12:34:56.789 +0300')
>>> a._tz
'+0300'
>>> a._timezone_naive
True
>>> a.tzoffset()
10800
>>> b = DateTime()
>>> b.__setstate__(a.__dict__) # using __dict__ as there is not __getstate__() in 2.12.8
>>> b._tz
'+0300'
>>> a == b
True
>>> a = DateTime('2007/01/02 12:34:56.789 +0430')
>>> a._tz
'+0430'
>>> a._timezone_naive
True
>>> a.tzoffset()
16200
>>> b = DateTime()
>>> b.__setstate__(a.__dict__) # using __dict__ as there is not __getstate__() in 2.12.8
>>> b._tz
'+0430'
>>> a == b
True
```

**Comment by jugmac00** [comment]
Please update to a more current version,
cf https://github.com/zopefoundation/DateTime/blob/master/CHANGES.rst#411-2016-04-30
